$jsonPath = "c:\Users\reed_\OneDrive\Desktop\Ranch at the Canyons HTML project\landholdings.json"
$jsPath = "c:\Users\reed_\OneDrive\Desktop\Ranch at the Canyons HTML project\data.js"

if (-not (Test-Path $jsonPath)) {
    Write-Error "Source JSON file not found: $jsonPath"
    exit 1
}

try {
    $data = Get-Content -Raw -Path $jsonPath | ConvertFrom-Json
    $cleanedData = @()

    foreach ($item in $data) {
        $cleanedItem = [ordered]@{}
        foreach ($prop in $item.psobject.Properties) {
            $name = $prop.Name
            $val = $prop.Value
            
            # Skip empty autogenerated column names
            if ($name -match "^Column_") {
                continue
            }
            # Trim and store
            if ($val -ne $null) {
                $cleanedItem[$name] = $val.ToString().Trim()
            } else {
                $cleanedItem[$name] = ""
            }
        }
        $cleanedData += $cleanedItem
    }

    # Format as a JavaScript constant declaration
    $jsonString = $cleanedData | ConvertTo-Json -Depth 5
    $jsContent = "const landholdings = $jsonString;"
    $jsContent | Out-File -FilePath $jsPath -Encoding utf8
    
    Write-Output "Successfully generated data.js with $($cleanedData.Count) cleaned lot records!"
} catch {
    Write-Error "Error generating data.js: $_"
}
